load("//schemas/crds:crd_codegen_groups.bzl", "crd_codegen_from_tree")
load("//schemas/crds:kcl_codegen_groups.bzl", "kcl_codegen_from_tree")

ALL_CRDS = glob(["**/*.yaml", "**/*.yml"])

PYTHON_GENERATORS = crd_codegen_from_tree(
    name_prefix = "gen",
    srcs = ALL_CRDS,
    namespace_prefix = "generated.models",
)

KCL_GENERATORS = kcl_codegen_from_tree(
    srcs = ALL_CRDS,
)

filegroup(
    name = "generated_python",
    srcs = PYTHON_GENERATORS,
    visibility = ["PUBLIC"],
)

filegroup(
    name = "generated_kcl",
    srcs = KCL_GENERATORS,
    visibility = ["PUBLIC"],
)
