python_bootstrap_library(
    name = "codegen_templates",
    srcs = glob(["templates/**"]),
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "codegen",
    main = "main.py",
    deps = [
        ":codegen_templates",
    ],
    visibility = ["PUBLIC"],
)
